
default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: <%= ENV['DEV_DB_PASS']%>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: hxh_world_4_development

test:
  <<: *default
  database: hxh_world_4_test

production:
  <<: *default
  database: hxh_world_4_production
  username: hxh_admin
  password: <%= ENV['PROD_DB_PASS'] %>
